In [2]:
import pandas as pd
import requests

In [4]:
responce=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [9]:
temp_df=pd.DataFrame(responce.json()['results'])[['id','title','overview','release_date','vote_count','popularity']]

In [10]:
temp_df

,id,title,overview,release_date,vote_count,popularity
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,1895,90.1445
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,30724,166.9172
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,3374,178.3103
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,23133,42.1520
4,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,5855,164.3082
5,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,14024,27.1930
6,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,17581,23.7019
7,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,10100,24.6732
8,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,705,21.1297
9,1383731,Protector,Nikki's life is shattered when her daughter is...,2026-02-20,411,19.2719
10,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,18505,36.4351
11,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,36050,40.1474
12,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,4600,13.7415
13,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,19405,26.7131
14,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,26801,36.8959
15,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,355,10.7759
16,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,20838,29.8527
17,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,30386,36.0912
18,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-07-01,12675,26.8368
19,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,40243,61.8413

In [13]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [12]:
temp_df.shape
# this actually done for only one page of api data

(20, 6)

In [35]:
# for fetching the entire data from all the pages 
# we have to run a loop 
for i in range(1,429):
  responce=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
  temp_df=pd.DataFrame(responce.json()['results'])[['id','title','overview','release_date','vote_count','popularity']]
  df=pd.concat([df,temp_df],ignore_index=True)

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [36]:
df.shape

(140, 6)

In [38]:
import requests
import pandas as pd

df = pd.DataFrame()

# Fetch data from all pages
for i in range(1, 151):
    response = requests.get(
        'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i)
    )

    temp_df = pd.DataFrame(response.json()['results'])[
        ['id', 'title', 'overview', 'release_date', 'vote_count', 'popularity']
    ]

    df = pd.concat([df, temp_df], ignore_index=True)

print(df.head())
print(df.shape)

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [39]:
df.shape

(220, 6)

In [41]:
df.head()

,id,title,overview,release_date,vote_count,popularity
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,1899,86.3449
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,30727,163.2599
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,3383,170.1650
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,23134,39.4047
4,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,5869,167.2060

In [ ]:
df.to_csv('mo')