In [6]:
import pandas as pd

In [1]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     - -------------------------------------- 0.5/11.9 MB 5.7 MB/s eta 0:00:02
     ---- ----------------------------------- 1.3/11.9 MB 5.4 MB/s eta 0:00:02
     ------- -------------------------------- 2.1/11.9 MB 4.4 MB/s eta 0:00:03
     -------- ------------------------------- 2.6/11.9 MB 3.6 MB/s eta 0:00:03
     ------------- -------------------------- 3.9/11.9 MB 4.4 MB/s eta 0:00:02
     --------------- ------------------------ 4.7/11.9 MB 4.3 MB/s eta 0:00:02
     ------------------ --------------------- 5.5/11.9 MB 4.1 MB/s eta 0:00:02
     ---------------------- ----------------- 6.6/11.9 MB 4.2 MB/s eta 0:00:02
     ----------------------- ---------------- 7.1/11.9 MB 4.1 MB/s eta 0:00:02
     -------------------------- ------------- 7.9/11.9 MB 4.1 MB/s eta 0:00:01
     ----------------------------- ---------- 8.7/11.9 MB 4.0 MB/s eta 0:00:01
     ------------------------------- -------- 9.4/11.9 MB 4.0 MB/s eta 0:00:01
     ---------------------------------- ----- 10.2/11.9 MB 4.0 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 4.0 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 4.0 MB/s  0:00:03
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248050 sha256=8768f726eff6c3ce081ae053c1841adc88642959f5217cb63c566c0342d58c0a
  Stored in directory: c:\users\sanke\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [2]:
import mysql.connector

In [3]:
conn=mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [7]:
pd.read_sql_query("SELECT * FROM city",conn)

C:\Users\sanke\AppData\Local\Temp\ipykernel_38232\374620591.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city",conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [12]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND'",conn)
# only those data will be printed which are from indian country code

C:\Users\sanke\AppData\Local\Temp\ipykernel_38232\3765274380.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND'",conn)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [14]:
pd.read_sql_query("SELECT * FROM city WHERE District  LIKE 'Maharashtra'",conn)

C:\Users\sanke\AppData\Local\Temp\ipykernel_38232\1955943185.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE District  LIKE 'Maharashtra'",conn)

      ID                        Name CountryCode     District  Population
0   1024             Mumbai (Bombay)         IND  Maharashtra    10500000
1   1032                      Nagpur         IND  Maharashtra     1624752
2   1034                        Pune         IND  Maharashtra     1566651
3   1041                      Kalyan         IND  Maharashtra     1014557
4   1049               Thane (Thana)         IND  Maharashtra      803389
5   1059              Nashik (Nasik)         IND  Maharashtra      656925
6   1061          Solapur (Sholapur)         IND  Maharashtra      604215
7   1065  Shambajinagar (Aurangabad)         IND  Maharashtra      573272
8   1070            Pimpri-Chinchwad         IND  Maharashtra      517083
9   1083                    Amravati         IND  Maharashtra      421576
10  1087                    Kolhapur         IND  Maharashtra      406370
11  1093                    Bhiwandi         IND  Maharashtra      379070
12  1095                  Ulhasnagar         IND  Maharashtra      369077
13  1098                    Malegaon         IND  Maharashtra      342595
14  1101                       Akola         IND  Maharashtra      328034
15  1106                  New Bombay         IND  Maharashtra      307297
16  1113              Dhule (Dhulia)         IND  Maharashtra      278317
17  1115             Nanded (Nander)         IND  Maharashtra      275083
18  1125                     Jalgaon         IND  Maharashtra      242193
19  1136                  Chandrapur         IND  Maharashtra      226105
20  1144                Ichalkaranji         IND  Maharashtra      214950
21  1155                       Latur         IND  Maharashtra      197408
22  1158                      Sangli         IND  Maharashtra      193197
23  1159                    Parbhani         IND  Maharashtra      190255
24  1168                  Ahmadnagar         IND  Maharashtra      181339
25  1172              Mira Bhayandar         IND  Maharashtra      175372
26  1174                       Jalna         IND  Maharashtra      174985
27  1218                    Bhusawal         IND  Maharashtra      145143
28  1254                       Miraj         IND  Maharashtra      125407
29  1292                  Bhir (Bid)         IND  Maharashtra      112434
30  1298                     Gondiya         IND  Maharashtra      109470
31  1300          Yeotmal (Yavatmal)         IND  Maharashtra      108578
32  1320                      Wardha         IND  Maharashtra      102985
33  1344                    Achalpur         IND  Maharashtra       96216
34  1348                      Satara         IND  Maharashtra       95133

In [15]:
pd.read_sql_query("SELECT * FROM country",conn)
# ab us database ka countryka data fetch hoga

C:\Users\sanke\AppData\Local\Temp\ipykernel_38232\858535147.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM country",conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW